learngit/project_django/shopping/commen/urls.py
from django.conf.urls import url

from .import views

app_name = 'commen'

urlpatterns = [
    url(r'^.*$', views.index, name='index')
]

learngit/project_django/shopping/goods/urls.py
from django.conf.urls import url

from . import views

app_name = 'goods'

urlpatterns = [
    url(r'^(?P<store_id>\d+)/goods_upload/$', views.goods_upload, name='goods_upload'),
    url(r'^(?P<goods_id>\d+)/goods_info/$', views.goods_info, name='goods_info'),
    url(r'^(?P<goods_id>\d+)/goods_update/$', views.goods_update, name='goods_update'),
    url(r'^goodstype/$', views.goodstype, name='goodstype'),
]

learngit/project_django/shopping/orders/urls.py
from django.conf.urls import url

from . import views

app_name = 'orders'

urlpatterns = [
    #结算确认,展示用户要购买的商品,同时检查是否有收货地址
    url(r'^order_confirm/$', views.order_confirm, name='order_confirm'),
    #结算付款,展示对应的付款页面,进行金钱操作
    url(r'^order_pay/$', views.order_pay, name='order_pay'),
    #生成订单
    url(r'^order_done/$', views.order_done, name='order_done'),
    #查询订单
    url(r'^order_list/$', views.order_list, name='order_list'),
    #查询订单详情
    url(r'^(?P<order_id>\d+)/order_info/$', views.order_info, name='order_info'),
]

learngit/project_django/shopping/shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^store/', include('store.urls')),
    url(r'^goods/', include('goods.urls')),
    url(r'^shopcart/', include('shopcart.urls')),
    url(r'^orders/', include('orders.urls')),
    url(r'^', include('commen.urls')),
]

learngit/project_django/shopping/goods/models.py
from django.db import models

import store

class GoodsType(models.Model):
    '''
    商品类型
    '''
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    cover = models.ImageField(upload_to='static/images/goodstype', default='static/images/goodstype/type.jpg')
    intro = models.TextField()

    parent = models.ForeignKey('self', null=True, blank=True)


class Goods(models.Model):
    '''
    商品数据模型
    '''
    id = models.AutoField(primary_key=True, verbose_name='商品编号')
    name = models.CharField(max_length=50, verbose_name='商品名称')
    price = models.FloatField(verbose_name='商品价格')
    stock = models.IntegerField(verbose_name='商品库存')
    sale = models .IntegerField(verbose_name='商品销量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='上架时间')
    intro = models.TextField(verbose_name='商品描述')

    goodstype = models.ForeignKey(GoodsType, on_delete=models.CASCADE, verbose_name='商品类型')
    store = models.ForeignKey(store.models.Store, on_delete=models.CASCADE, verbose_name='所属商店')



class GoodsImage(models.Model):
    '''
    商品图片： 商品-商品图片
    '''
    id = models.AutoField(primary_key=True)
    path = models.ImageField(upload_to='static/images/goods')
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)

learngit/project_django/shopping/orders/models.py
from django.db import models
from django.contrib.auth.models import User


class MyOrder(models.Model):
    '''
    订单数据模型
    '''
    id = models.AutoField(primary_key=True)
    order_time = models.DateTimeField(auto_now_add=True, verbose_name='下单时间')
    address = models.CharField(max_length=200, verbose_name='收货地址')
    total = models.FloatField(verbose_name='总计金额')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class MyOrderItem(models.Model):
    '''
    订单中的购物对象模型
    '''
    id = models.AutoField(primary_key=True)
    goods_img = models.ImageField(upload_to='static/images/goods/')
    goods_name = models.CharField(max_length=20, verbose_name='商品名称')
    goods_price = models.FloatField(verbose_name='成交价格')
    goods_count = models.IntegerField(verbose_name='购买数量')
    goods_subtotal = models.FloatField(verbose_name='小计金额')

    myorder = models.ForeignKey(MyOrder, on_delete=models.CASCADE)

learngit/project_django/shopping/users/models.py
from django.db import models
#导入Django框架内置的用户模块
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    '''
    定义一个用户扩展类型
    和系统内置用户一对一关联
    '''
    #定义扩展属性字段
    id = models.AutoField(primary_key=True)
    header = models.ImageField(upload_to='static/images/headers/', default='static/images/headers/default.jpg')
    nickname = models.CharField(max_length=50)
    phone = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=5)

    #和系统内置用户关联
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class Address(models.Model):
    '''
    用户地址
    '''
    id = models.AutoField(primary_key=True)
    recv = models.CharField(max_length=50, verbose_name='收件人')
    phone = models.CharField(max_length=20, verbose_name='联系方式')
    nation = models.CharField(max_length=50, verbose_name='国家')
    province = models.CharField(max_length=50, verbose_name='省区')
    city = models.CharField(max_length=50, verbose_name='市区')
    country = models.CharField(max_length=50, verbose_name='县区')
    street = models.CharField(max_length=50, verbose_name='街道')
    intro = models.TextField(verbose_name='详细地址')
    status = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

learngit/project_django/shopping/orders/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

import shopcart,users
from . import models
# Create your views here.
def order_confirm(request):
    '''
    结算确认
    :param request:
    :return:
    '''
    #获取数据
    shopcart_id_list = request.POST.getlist('buy_goods_id')
    print(shopcart_id_list)
    shopcart_list = shopcart.models.Shopcart.objects.filter(pk__in=shopcart_id_list)
    print(shopcart_list)
    return render(request, 'orders/order_confirm.html', {'shopcart_list': shopcart_list})



def order_pay(request):
    '''
    结算付款
    :param request:
    :return:
    '''

    pass


def order_done(request):
    '''
    生成订单
    :param request:
    :return:
    '''
    #获取购买的商品
    shopcart_list = request.POST.getlist('sc')
    #获取收货地址
    addr_id = request.POST['addr_id']
    address = users.models.Address.objects.get(pk=addr_id)
    #拼接地址
    addr = address.recv + ";" + address.phone + ";" + address.nation + ";" + address.province \
           + ";" + address.city + ";" + address.country + ";" + address.street + ";" + address.intro
    total = 0
    #生成订单
    myorder = models.MyOrder(user=request.user, address=addr, total=total)
    myorder.save()
    #创建订单对象
    for sc_id in shopcart_list:
        #查询购物对象
        _shopcart = shopcart.models.Shopcart.objects.get(pk=sc_id)
        #创建订单对象
        order_item = models.MyOrderItem(goods_img=_shopcart.goods.goodsimage_set.first().path,\
                                        goods_name=_shopcart.goods.name,\
                                        goods_price=_shopcart.goods.price,\
                                        goods_count=_shopcart.count,\
                                        goods_subtotal=_shopcart.subtoal,\
                                        myorder=myorder
                                        )
        order_item.save()
        #计算总金额
        total += _shopcart.subtoal
    #更新总金额
    myorder.total =total
    myorder.save()
    #保存跳转到订单详情页面
    return redirect(reverse('orders:order_info', kwargs={'order_id': myorder.id}))


def order_list(request):
    '''
    查询所有订单
    :param request:
    :return:
    '''

    order_list = models.MyOrder.objects.filter(user=request.user)
    return render(request, 'orders/order_list.html', {'order_list': order_list})

def order_info(request,order_id):
    '''
    订单详情
    :param request:
    :return:
    '''
    #查询订单
    _order = models.MyOrder.objects.get(pk=order_id)
    return render(request, 'orders/order_info.html', {'order': _order})

learngit/project_django/shopping/orders/templates/orders/order_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>确认订单</h2>
<h4>请确认你的购买的商品信息</h4>
<h4><a href="{% url 'commen:index' %}">首页</a></h4>
{% for shopcart in shopcart_list %}
<div>
    <img style="width: 200px; height: 200px" src="/{{shopcart.goods.goodsimage_set.all.first.path}}" alt=""><br>
    <span>名称:{{shopcart.goods.name}}</span>
    <span>数量:{{shopcart.count}}</span>
    <span>小计金额:{{shopcart.subtoal}}</span>
</div>
<hr>
{% endfor %}
<h3>提交付款</h3>
<form action="{% url 'orders:order_done' %}" method="POST">
    {% csrf_token %}
    <!--传回收货地址和商品id-->
    {% for sc in shopcart_list %}
    <input type="hidden" name="sc" value="{{sc.id}}">
    {% endfor %}
    选择收货地址: <br>
    <!--展示用户所有收货地址-->
    {% for address in shopcart_list.first.user.address_set.all %}
    {% if address.status %}
    <input type="radio" name="addr_id" checked value="{{address.id}}">
    {{address.recv}}-{{address.phone}}-{{address.nation}}-{{adress.province}}-{{address.city}}-{{address.country}}-{{address.street}}-{{address.intro}}
    <br>
    {% else %}
     <input type="radio" name="addr_id"  value="{{address.id}}">
    {{address.recv}}-{{address.phone}}-{{address.nation}}-{{adress.province}}-{{address.city}}-{{address.country}}-{{address.street}}-{{address.intro}}
    <br>
    {% endif %}
    {% empty %}
    <div>当前用户还没有收货地址,请 <a href="#">添加收货地址</a></div>
    {% endfor %}
    <input type="submit" value="提交订单">
</form>
</body>
</html>

learngit/project_django/shopping/orders/templates/orders/order_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>查看订单详情</h3>
<h4><a href="{% url 'commen:index' %}">首页</a></h4>
<div>
    订单编号:{{order.id}}
    <p>下单时间: {{order.order_time|date:'Y-m-d G:i:s'}}</p>
    <p>收货地址: {{order.address}}</p>
    <p>总计金额: {{order.total}}</p>
</div>
<hr>
<div style="width: 800px;">
    {% for orderitem in order.myorderitem_set.all %}
    <p><img style="width: 200px; height: 200px" src="/{{orderitem.goods_img}}" alt=""></p>
    <p>商品名称:{{orderitem.goods_name}}</p>
    <p>成交价格:{{orderitem.goods_price}}</p>
    <p>购买数量:{{orderitem.goods_count}}</p>
    <p>小计金额:{{orderitem.goods_subtotal}}</p>
    {% empty %}
    <p>没有购买商品</p>
    {% endfor %}
</div>
</body>
</html>

learngit/project_django/shopping/orders/templates/orders/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>查看个人订单</h2>
{% for order in order_list %}
<li>订单编号: {{order.id}}|下单时间:{{order.order_time|date:'Y-m-d G:i:s'}}
<a href="{% url 'orders:order_info' order.id %}">查看订单详情</a>
</li>
{% empty %}
<li>您还没有任何订单</li>
{% endfor %}
</body>
</html>

learngit/project_django/shopping/orders/templates/orders/order_pay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>