learngit/project_django/shopping/commen/urls.py
from django.conf.urls import url

from .import views

app_name = 'commen'

urlpatterns = [
    url(r'^.*$', views.index, name='index')
]

learngit/project_django/shopping/goods/urls.py
from django.conf.urls import url

from . import views

app_name = 'goods'

urlpatterns = [
    url(r'^(?P<store_id>\d+)/goods_upload/$', views.goods_upload, name='goods_upload'),
    url(r'^(?P<goods_id>\d+)/goods_info/$', views.goods_info, name='goods_info'),
    url(r'^(?P<goods_id>\d+)/goods_update/$', views.goods_update, name='goods_update'),
    url(r'^goodstype/$', views.goodstype, name='goodstype'),
]

learngit/project_django/shopping/orders/urls.py
from django.conf.urls import url

from . import views

app_name = 'orders'

urlpatterns = [
    #结算确认,展示用户要购买的商品,同时检查是否有收货地址
    url(r'^order_confirm/$', views.order_confirm, name='order_confirm'),
    #结算付款,展示对应的付款页面,进行金钱操作
    url(r'^order_pay/$', views.order_pay, name='order_pay'),
    #生成订单
    url(r'^order_done/$', views.order_done, name='order_done'),
    #查询订单
    url(r'^order_list/$', views.order_list, name='order_list'),
    #查询订单详情
    url(r'^(?P<order_id>\d+)/order_info/$', views.order_info, name='order_info'),
]

learngit/project_django/shopping/shopcart/urls.py
from django.conf.urls import url

from . import views

app_name = 'shopcart'

urlpatterns = [
    url(r'(?P<goods_id>\d+)/(?P<count>\d+)/shopcart_add', views.shopcart_add, name='shopcart_add'),
    url(r'shopcart_info/', views.shopcart_info, name='shopcart_info'),

]

learngit/project_django/shopping/shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^store/', include('store.urls')),
    url(r'^goods/', include('goods.urls')),
    url(r'^shopcart/', include('shopcart.urls')),
    url(r'^orders/', include('orders.urls')),
    url(r'^', include('commen.urls')),
]

learngit/project_django/shopping/store/urls.py
from django.conf.urls import url

from . import views

app_name = 'store'

urlpatterns = [
    url(r'^store_add/$', views.store_add, name='store_add'),
    url(r'^(?P<store_id>\d+)/store_info/$', views.store_info, name='store_info'),
    url(r'^(?P<store_id>\d+)/store_close/$', views.store_close, name='store_close'),
    url(r'^(?P<store_id>\d+)/store_delete/$', views.store_delete, name='store_delete'),
    url(r'^store_list/$', views.store_list, name='store_list'),
    url(r'^(?P<store_id>\d+)/store_update/$', views.store_update, name='store_update'),

]

learngit/project_django/shopping/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    url(r'^register/$', views.user_register, name='user_register'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^address_add/$', views.address_add, name='address_add'),
    url(r'^address_list/$', views.address_list, name='address_list'),
]

learngit/project_django/shopping/commen/models.py
from django.db import models

# Create your models here.

learngit/project_django/shopping/commen/views.py
from django.shortcuts import render
#require_GET装饰器，一般定义在视图函数上，指定视图函数的访问方式
from django.views.decorators.http import require_GET
#login_require装饰器，一般定义在视图函数上，只允许装饰函数的在用户登录之后才能访问
from django.contrib.auth.decorators import login_required

import goods, store

# Create your views here.
# @login_required
@require_GET
def index(request):
    '''
    只允许get方式访问
    :param request:
    :return:
    '''
    # if request.method == 'GET':
    #     return render(request, 'commen/index.html',{})
    #查询所有的商品类型，在首页中展示所有类型
    goodstype_1_list = goods.models.GoodsType.objects.filter(parent__isnull=True)
    #查询所有类型中指定的数据[切片]
    #(1)手机|数码
    goods_type_1 = goods.models.GoodsType.objects.get(pk=1)
    goods_type_1_list = goods.models.GoodsType.objects.filter(parent=goods_type_1)
    goods_list_1 = goods.models.Goods.objects.filter(goodstype__in=goods_type_1_list)[0:5]
    #(2)家居|家装
    goods_type_2 = goods.models.GoodsType.objects.get(pk=2)
    goods_type_2_list = goods.models.GoodsType.objects.filter(parent=goods_type_2)
    goods_list_2 = goods.models.Goods.objects.filter(goodstype__in=goods_type_2_list)[0:5]
    #(3)男装|女装
    goods_type_3 = goods.models.GoodsType.objects.get(pk=3)
    goods_type_3_list = goods.models.GoodsType.objects.filter(parent=goods_type_3)
    goods_list_3 = goods.models.Goods.objects.filter(goodstype__in=goods_type_3_list)[0:5]
    #热门店铺
    store_list = store.models.Store.objects.all()[0:5]
    return render(request, 'commen/index.html', {'goodstype_1_list': goodstype_1_list,\
                                                 'goods_list_1': goods_list_1,\
                                                 'goods_list_2': goods_list_2,\
                                                 'goods_list_3': goods_list_3,\
                                                 'store_list': store_list
                                                 })

learngit/project_django/shopping/commen/templates/commen/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'commen/css/style.css' %}">
    <script src="{% static 'commen/js/lib/jQuery/jquery-2.1.4.js' %}"></script>
    <script src="{% static 'commen/js/app/index.js' %}"></script>

</head>
<body>
<h2>电商首页</h2>
{{request.user}}
{{error_msg}}
<h3><a href="{% url 'users:user_login' %}">用户登录</a></h3>
<h3><a href="{% url 'users:user_register' %}">用户注册</a></h3>
<h3><a href="{% url 'store:store_list' %}">查看个人店铺</a></h3>
<h3><a href="{% url 'shopcart:shopcart_info' %}">查看购物车</a></h3>
<h3><a href="{% url 'orders:order_list' %}">查看订单</a></h3>
<h3><a href="{% url 'store:store_add' %}">开设店铺</a></h3>
<h3><a href="{% url 'users:address_add' %}">添加地址</a></h3>
<h3><a href="{% url 'users:address_list' %}">查看地址</a></h3>
<a href="{% url 'users:user_logout' %}">安全退出</a>
<h4><a href="{% url 'commen:index' %}">首页</a></h4>
<hr>
<ul class="type1">
    {% for goodstype in goodstype_1_list %}
    <li class="type2li"><a href="">{{goodstype.name}}</a>
        <!--展示商品二级类型-->
        <ul class="type2">
            {% for goodstype2 in goodstype.goodstype_set.all %}
            <li><a href="">{{goodstype2.name}}</a></li>
            {% empty %}
            <li>当前没有二级商品类型</li>
            {% endfor %}
        </ul>
    </li>
    {% empty %}
    <li>当前没有任何商品类型</li>
    {% endfor %}
    <hr>
    <div id="goodscontainer">
        <h3 class="goodstitle">手机数码</h3>
        {% for goods in goods_list_1 %}
        <div class="goodsbox">
            <p class="goodsimg"><img src="/{{goods.goodsimage_set.all.first.path}}" alt=""></p>
            <p class="goodsname">名称:{{goods.name}}</p>
            <p class="goodsprice">价格:{{goods.price}}</p>
            <p><a href="{% url 'goods:goods_info' goods.id %}">查看详情</a>
                <a class="addcart" goodsid="{{goods.id}}">加入购物车</a>
            </p>
        </div>
        {% endfor %}
        <h3 class="goodstitle">家居家装</h3>
        {% for goods in goods_list_2 %}
        <div class="goodsbox">
            <p class="goodsimg"><img src="/{{goods.goodsimage_set.all.first.path}}" alt=""></p>
            <p class="goodsname">名称:{{goods.name}}</p>
            <p class="goodsprice">价格:{{goods.price}}</p>
            <p><a href="{% url 'goods:goods_info' goods.id %}">查看详情</a>
                <a class="addcart" goodsid="{{goods.id}}">加入购物车</a>
            </p>

        </div>
        {% endfor %}
        <h3 class="goodstitle">男装女装</h3>
        {% for goods in goods_list_3 %}
        <div class="goodsbox">
            <p class="goodsimg"><img src="/{{goods.goodsimage_set.all.first.path}}" alt=""></p>
            <p class="goodsname">名称:{{goods.name}}</p>
            <p class="goodsprice">价格:{{goods.price}}</p>
            <p><a href="{% url 'goods:goods_info' goods.id %}">查看详情</a>
                <a class="addcart" goodsid="{{goods.id}}">加入购物车</a>

            </p>

        </div>
        {% endfor %}
        <hr>
        <h3 class="goodstitle">热门店铺</h3>
        {% for store in store_list %}
        {% if store.status != 2 %}
        <div class="goodsbox">
            <p class="goodsimg"><img src="/{{store.cover}}" alt=""></p>
            <p class="goodsname">{{store.name}}</p>
            <!--<p>{{store.status}}</p>-->
            <p>
                <a href="{% url 'store:store_info' store.id %}">查看详情</a>
            </p>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</ul>

</body>
</html>