learngit/project_django/shopping/commen/urls.py
from django.conf.urls import url

from .import views

app_name = 'commen'

urlpatterns = [
    url(r'^.*$', views.index, name='index')
]

learngit/project_django/shopping/goods/urls.py
from django.conf.urls import url

from . import views

app_name = 'goods'

urlpatterns = [
    url(r'^(?P<store_id>\d+)/goods_upload/$', views.goods_upload, name='goods_upload'),
    url(r'^(?P<goods_id>\d+)/goods_info/$', views.goods_info, name='goods_info'),
    url(r'^(?P<goods_id>\d+)/goods_update/$', views.goods_update, name='goods_update'),
    url(r'^goodstype/$', views.goodstype, name='goodstype'),
]

learngit/project_django/shopping/shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^store/', include('store.urls')),
    url(r'^goods/', include('goods.urls')),
    url(r'^shopcart/', include('shopcart.urls')),
    url(r'^orders/', include('orders.urls')),
    url(r'^', include('commen.urls')),
]

learngit/project_django/shopping/store/urls.py
from django.conf.urls import url

from . import views

app_name = 'store'

urlpatterns = [
    url(r'^store_add/$', views.store_add, name='store_add'),
    url(r'^(?P<store_id>\d+)/store_info/$', views.store_info, name='store_info'),
    url(r'^(?P<store_id>\d+)/store_close/$', views.store_close, name='store_close'),
    url(r'^(?P<store_id>\d+)/store_delete/$', views.store_delete, name='store_delete'),
    url(r'^store_list/$', views.store_list, name='store_list'),
    url(r'^(?P<store_id>\d+)/store_update/$', views.store_update, name='store_update'),

]

learngit/project_django/shopping/goods/models.py
from django.db import models

import store

class GoodsType(models.Model):
    '''
    商品类型
    '''
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    cover = models.ImageField(upload_to='static/images/goodstype', default='static/images/goodstype/type.jpg')
    intro = models.TextField()

    parent = models.ForeignKey('self', null=True, blank=True)


class Goods(models.Model):
    '''
    商品数据模型
    '''
    id = models.AutoField(primary_key=True, verbose_name='商品编号')
    name = models.CharField(max_length=50, verbose_name='商品名称')
    price = models.FloatField(verbose_name='商品价格')
    stock = models.IntegerField(verbose_name='商品库存')
    sale = models .IntegerField(verbose_name='商品销量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='上架时间')
    intro = models.TextField(verbose_name='商品描述')

    goodstype = models.ForeignKey(GoodsType, on_delete=models.CASCADE, verbose_name='商品类型')
    store = models.ForeignKey(store.models.Store, on_delete=models.CASCADE, verbose_name='所属商店')



class GoodsImage(models.Model):
    '''
    商品图片： 商品-商品图片
    '''
    id = models.AutoField(primary_key=True)
    path = models.ImageField(upload_to='static/images/goods')
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)

learngit/project_django/shopping/store/models.py
from django.db import models
from django.contrib.auth.models import User


class Store(models.Model):
    '''
    店铺数据模型
    '''
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    cover = models.ImageField(upload_to='static/images/store/', default='static/images/store/store.jpg')
    status = models.IntegerField(default=0)# 0正常 1关闭 2删除 其他~永久删除
    intro = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

learngit/project_django/shopping/store/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET
from . import models


# Create your views here.
@login_required
def store_add(request):
    '''
    添加店铺操作函数
    :param request:
    :return:
    '''
    if request.method == 'GET':
        return render(request, 'store/store_add.html', {})
    elif request.method == 'POST':
        # 获取数据
        name = request.POST['name']
        intro = request.POST['intro']
        user = request.user
        try:
            cover = request.FILES['cover']
            store = models.Store(name=name, intro=intro, user=user, cover=cover)
        except:
            store = models.Store(name=name, intro=intro, user=user)
        store.save()
        return render(request, 'store/store_add.html', {"error_code": 0, "error_msg": "开店成功"})


@login_required
@require_GET
def store_list(request):
    '''
    查看所有店铺函数
    :param request:
    :return:
    '''
    # if request.method == 'GET':
    #     return render(request, 'store/store_list.html', {})
    store_list = models.Store.objects.filter(user=request.user, status__in=[0, 1])
    return render(request, 'store/store_list.html', {'store_list': store_list})


@login_required
@require_GET
def store_info(request, store_id):
    '''
    店铺详情函数
    :param request:
    :return:
    '''
    # if request.method == 'GET':
    #     return render(request, 'store/store_info.html', {})
    store = models.Store.objects.get(pk=store_id)
    return render(request, 'store/store_info.html', {"store": store})


@login_required
def store_update(request, store_id):
    '''
    修改店铺视图函数
    :param request:
    :return:
    '''
    store = models.Store.objects.get(pk=store_id)
    if request.method == 'GET':
        return render(request, 'store/store_update.html', {"store": store})
    elif request.method == 'POST':
        #获取数据
        name = request.POST['name']
        intro = request.POST['intro']
        status = request.POST['status']

        try:
            cover = request.FILES['cover']
            store.cover = cover
        except:
            pass
        store.name = name
        store.intro = intro
        store.status = status

        store.save()
        return redirect(reverse('store:store_info', kwargs={'store_id': store.id}))



@login_required
@require_GET
def store_close(request, store_id):
    '''
    关闭店铺
    :param request:
    :param store_id:
    :return:
    '''
    store = models.Store.objects.get(pk=store_id)
    store.status = 1
    store.save()
    return redirect(reverse('store:store_info', kwargs={'store_id': store.id}))


@login_required
@require_GET
def store_delete(request, store_id):
    '''
    删除店铺
    :param request:
    :param store_id:
    :return:
    '''
    store = models.Store.objects.get(pk=store_id)
    store.status = 2
    store.save()
    return redirect(reverse('store:store_list'))

learngit/project_django/shopping/store/templates/store/store_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>开店</h2>
{{error_code}}{{error_msg}}
<form action="{% url 'store:store_add' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    店名：<input type="text" name="name" id="name"><br>
    门面：<input type="file" name="cover" id="cover"><br>
    店铺描述：<textarea name="intro" id="intro" cols="30" rows="10"></textarea><br>
    <input type="submit" value="开业大吉">
    <h4><a href="{% url 'commen:index' %}">首页</a></h4>

</form>
</body>
</html>

learngit/project_django/shopping/store/templates/store/store_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
<h2>店铺详情</h2>
<table border="1">
    <tr>
        <td>店铺封面</td>
        <td><img  width="750px" height="450px" src="/{{store.cover}}" alt=""></td>
    </tr>
    <tr>
        <td>店铺状态</td>
        <td>
            {% if store.status == 0 %}
            正常营业
            {% elif store.status == 1 %}
            暂停营业
            {% elif store.status == 2 %}
            店铺已经删除，如果要回复店铺，请联系管理员
            {% endif %}
        </td>
    </tr>
    <tr>
        <td>店铺描述</td>
        <td>{{store.intro}}</td>
    </tr>
    <tr>
        <td>店铺操作</td>
        <td>
            <a href="{% url 'goods:goods_upload' store.id%}">上传商品</a>
            <a href="{% url 'store:store_update' store.id%}">修改店铺</a>
            <a href="{% url 'store:store_close' store.id%}">关闭店铺</a>
            <a href="{% url 'store:store_delete' store.id%}">删除店铺</a>
        </td>
    </tr>
</table>
<h4><a href="{% url 'commen:index' %}">首页</a></h4>
<hr>
<h2>店铺内的商品</h2>
{% for goods in store.goods_set.all %}
<div>
    <p><img  width="800px" src="/{{goods.goodsimage_set.all.first.path}}" alt=""></p>
    <p>商品名称{{goods.name}}</p>
    <p>商品单价{{goods.price}}</p>
    <p>商品库存{{goods.stock}}</p>
    <p>商品销量{{goods.sell}}</p>
    <p>
        <a href="{% url 'goods:goods_info' goods.id %}"> 查看详情</a>
        <a href="{% url 'goods:goods_update' goods.id %}">修改商品</a>
        <a href="">删除商品</a>
    </p>
</div>
<hr>
{% empty %}
您的店铺还有上架任何商品
{% endfor %}
</body>
</html>

learngit/project_django/shopping/store/templates/store/store_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>查看自己的店铺</h2>
<h4><a href="{% url 'commen:index' %}">首页</a></h4>
<ul>
    {% for store in store_list %}
    <li>
        <img src="/{{store.cover}}" alt=""><br>
        <p>{{store.name}}</p>
        <p>{{store.intro}}</p>
        <p><a href="{% url 'store:store_info' store.id%}">查看店铺详情</a></p>
    </li>
    <hr>
    {% empty %}
    <li>您还没有开设任何店铺</li>
    {% endfor %}
</ul>
</body>
</html>

learngit/project_django/shopping/store/templates/store/store_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>店铺维护</h2>
<form action="{% url 'store:store_update' store.id%}" method="POST"
      enctype="multipart/form-data">
    {% csrf_token %}
    店铺名称：<input type="text" name="name" id="name" value="{{store.name}}"><br/>
    店铺封面：<input type="file" name="cover" id="cover"><br/>
    店铺描述：<textarea name="intro" id="intro" cols="30" rows="10">{{store.intro}}</textarea><br/>
    店铺状态：<input type="radio" checked name="status" id="0" value="0">正常营业<br/>
    <input type="radio" name="status" id="1" value="1">暂停营业<br/>
    <input type="radio"  name="status" id="2" value="2">删除店铺<br/>
    <input type="submit" value="提交">
</form>
</body>